## Log Reg

In [2]:
import pandas as pd
mod=pd.read_csv("E:\PrajaktaR\DataSets/modeldata.csv")
mod.head()

id extract_date     skill       job  \
0  0002e93c8519f24cc642ca462ef49956    10/1/2017  BEGINNER  ACADEMIC   
1  0003b2d98410d0350070961653b8c3bc    10/1/2017  BEGINNER  ACADEMIC   
2  00093099e0d8d7c3d60a22e2883ad63d    10/1/2017  BEGINNER       NaN   
3  000eb7f4b843c451d98a249e85328b05    10/1/2017  BEGINNER   STUDENT   
4  001134540564124eb2f767cb0905053c    10/1/2017  BEGINNER   STUDENT   

              purpose             target_group business_group  \
0     ME_PROFESSIONAL       HED - ED/FAC/STAFF      EDUCATION   
1     ME_PROFESSIONAL  EDGEN - AD/ED/FAC/STAFF      EDUCATION   
2                 NaN                 HOBBYIST       HOBBYIST   
3  ME_NONPROFESSIONAL          EDGEN - STUDENT      EDUCATION   
4     ME_PROFESSIONAL          EDGEN - STUDENT      EDUCATION   

    business_segment            signup_source signup_category  \
0  EDU STUDENT STAFF           Creative Cloud         DESKTOP   
1  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   
2              PHOTO               Draw (iOS)          MOBILE   
3  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   
4  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   

  first_cc_subscription_dts country_code product_id  download_attempts  \
0           3/12/2017 11:44           US  PHSP:APRO                2.0   
1           5/29/2017 15:35           US       APRO                1.0   
2            6/10/2017 1:04           US  ILST:PHSP                3.0   
3           1/21/2017 18:33           US   PPRO:AME                2.0   
4           6/23/2017 14:46           US       IDSN                1.0   

  product_platforms  machines error_codes  label  
0               MAC       1.0         NaN      0  
1               WIN       0.0         NaN      0  
2           MAC:WIN       1.0         NaN      0  
3               WIN       1.0         NaN      0  
4               MAC       0.0         NaN      0

In [3]:
mod=mod.drop(["id","extract_date","first_cc_subscription_dts","error_codes"],axis=1)

In [4]:
mod.head()

skill       job             purpose             target_group  \
0  BEGINNER  ACADEMIC     ME_PROFESSIONAL       HED - ED/FAC/STAFF   
1  BEGINNER  ACADEMIC     ME_PROFESSIONAL  EDGEN - AD/ED/FAC/STAFF   
2  BEGINNER       NaN                 NaN                 HOBBYIST   
3  BEGINNER   STUDENT  ME_NONPROFESSIONAL          EDGEN - STUDENT   
4  BEGINNER   STUDENT     ME_PROFESSIONAL          EDGEN - STUDENT   

  business_group   business_segment            signup_source signup_category  \
0      EDUCATION  EDU STUDENT STAFF           Creative Cloud         DESKTOP   
1      EDUCATION  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   
2       HOBBYIST              PHOTO               Draw (iOS)          MOBILE   
3      EDUCATION  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   
4      EDUCATION  EDU STUDENT STAFF  Renga Auto Provisioning         DESKTOP   

  country_code product_id  download_attempts product_platforms  machines  \
0           US  PHSP:APRO                2.0               MAC       1.0   
1           US       APRO                1.0               WIN       0.0   
2           US  ILST:PHSP                3.0           MAC:WIN       1.0   
3           US   PPRO:AME                2.0               WIN       1.0   
4           US       IDSN                1.0               MAC       0.0   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
mod.isnull().sum()

skill                     0
job                  164644
purpose              164660
target_group              0
business_group            0
business_segment         25
signup_source             0
signup_category           0
country_code              0
product_id           113298
download_attempts    113298
product_platforms    113298
machines             113298
label                     0
dtype: int64

In [6]:
mod.job=mod.job.fillna("other")
mod.purpose=mod.purpose.fillna("null")
mod.business_segment=mod.business_segment.fillna("0")
mod.product_id=mod.product_id.fillna("A")
mod.download_attempts=mod.download_attempts.fillna(mod.download_attempts.mean())
mod.machines=mod.machines.fillna(mod.machines.mean())
mod.product_platforms=mod.product_platforms.fillna("W")

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [8]:
X=mod
for i in range(0,X.shape[1]):
    if X.dtypes[i]=='object':
        X[X.columns[i]]=le.fit_transform(X[X.columns[i]])

In [9]:
mod.head()

skill  job  purpose  target_group  business_group  business_segment  \
0      0    0        1            17               5                 2   
1      0    0        1            12               5                 2   
2      0   14        5            19               6                 5   
3      0   10        0            13               5                 2   
4      0   10        1            13               5                 2   

   signup_source  signup_category  country_code  product_id  \
0             24                1            38       24328   
1             85                1            38        7313   
2             27                3            38       17507   
3             85                1            38       28424   
4             85                1            38       12938   

   download_attempts  product_platforms  machines  label  
0                2.0                  0       1.0      0  
1                1.0                  3       0.0      0  
2                3.0                  1       1.0      0  
3                2.0                  3       1.0      0  
4                1.0                  0       0.0      0

In [10]:
mod_x=mod.drop(["label"],axis=1)
mod_y=mod.label

In [11]:
from sklearn.model_selection import train_test_split
mod_x_train,mod_x_test,mod_y_train,mod_y_test=train_test_split(mod_x,mod_y,test_size=0.2,random_state=101)

In [11]:
mod_x_train.shape

(247158, 13)

In [12]:
mod_y_train.shape

(247158,)

In [13]:
mod_x_test.shape

(61790, 13)

In [14]:
mod_y_test.shape

(61790,)

In [89]:
from sklearn.linear_model import LogisticRegression
mod_log=LogisticRegression()
mod_log.fit(mod_x_train,mod_y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [90]:
pred1=mod_log.predict(mod_x_test)

In [91]:
from sklearn.metrics import confusion_matrix
tab1=confusion_matrix(pred1,mod_y_test)
tab1

array([[58404,  3386],
       [    0,     0]], dtype=int64)

In [92]:
tab1.diagonal().sum()/tab1.sum()

0.9452014889140637

In [102]:
import numpy as np
np.unique(pred1)

array([0], dtype=int64)

In [123]:
#over sampling
from sklearn.utils import resample
df_majority=mod[mod.label==0]
df_minority=mod[mod.label==1]

In [124]:
mod.label.value_counts()

0    292369
1     16579
Name: label, dtype: int64

In [125]:
df_mod=resample(df_minority,replace=True,n_samples=292369,random_state=101)

In [126]:
mod_new=pd.concat([df_majority, df_mod])

In [127]:
mod_new_x=mod_new.drop(["label"],axis=1)
mod_new_y=mod_new.label

In [129]:
from sklearn.model_selection import train_test_split
mod_x_train,mod_x_test,mod_y_train,mod_y_test=train_test_split(mod_new_x,mod_new_y,test_size=0.2,random_state=101)

In [134]:
from sklearn.linear_model import LogisticRegression
mod_log=LogisticRegression()
mod_log.fit(mod_x_train,mod_y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [135]:
pred_new=mod_log.predict(mod_x_test)

In [137]:
from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_new,mod_y_test)
tab

array([[34686, 24278],
       [23961, 34023]], dtype=int64)

In [138]:
tab.diagonal().sum()/tab.sum()

0.5875175291582584

## Decision Tree

In [93]:
from sklearn.tree import DecisionTreeClassifier
mod_dt=DecisionTreeClassifier()
mod_dt.fit(mod_x_train,mod_y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [94]:
pred2=mod_dt.predict(mod_x_test)

In [95]:
from sklearn.metrics import confusion_matrix
tab2=confusion_matrix(pred2,mod_y_test)
tab2

array([[56494,  3143],
       [ 1910,   243]], dtype=int64)

In [96]:
tab2.diagonal().sum()/tab2.sum()

0.9182230134325943

## Random Forest

In [98]:
from sklearn.ensemble import RandomForestClassifier
mod_rfc=RandomForestClassifier()
mod_rfc.fit(mod_x_train,mod_y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [99]:
pred3=mod_rfc.predict(mod_x_test)

In [100]:
from sklearn.metrics import confusion_matrix
tab3=confusion_matrix(pred3,mod_y_test)
tab3

array([[57934,  3310],
       [  470,    76]], dtype=int64)

In [101]:
tab3.diagonal().sum()/tab3.sum()

0.9388250525975077

In [218]:
mod_x=mod
mod_y=mod.label

In [219]:
from sklearn.model_selection import train_test_split
mod_x_train,mod_x_test,mod_y_train,mod_y_test=train_test_split(mod_x,mod_y,test_size=0.2,random_state=101)

In [220]:
# from over sampling
from sklearn.utils import resample
df_majority=mod_x_train[mod_x_train.label==0]
df_minority=mod_x_train[mod_x_train.label==1]

In [235]:
df_mod=resample(df_minority,replace=True,n_samples=,random_state=101)

In [236]:
mod_new=pd.concat([df_majority, df_mod])
mod_new.label.value_counts()

0    233965
1      2000
Name: label, dtype: int64

In [223]:
mod_new_x=mod_new.drop(["label"],axis=1)
mod_new_y=mod_new.label

In [203]:
#from sklearn.model_selection import train_test_split
#mod_x_train,mod_x_test,mod_y_train,mod_y_test=train_test_split(mod_new_x,mod_new_y,test_size=0.2,random_state=101)

In [224]:
from sklearn.ensemble import RandomForestClassifier
mod_rfc=RandomForestClassifier()
mod_rfc.fit(mod_new_x,mod_new_y)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [226]:
pred=mod_rfc.predict(mod_new_x)

In [227]:
from sklearn.metrics import confusion_matrix
tab4=confusion_matrix(pred,mod_new_y)
tab4

array([[201966,  33921],
       [ 31999, 258448]], dtype=int64)

In [228]:
tab4.diagonal().sum()/tab4.sum()

0.8747563334308633

In [231]:
mod.label.value_counts()

0    292369
1     16579
Name: label, dtype: int64

In [237]:
mod_x_train.label.value_counts()

0    233965
1     13193
Name: label, dtype: int64

## Adaptive Boosting

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [17]:
abc=AdaBoostClassifier(DecisionTreeClassifier(),n_estimators=15)
abc.fit(mod_x_train,mod_y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                          

In [20]:
pred5=abc.predict(mod_x_test)
pred5

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
tab5=confusion_matrix(pred5,mod_y_test)
tab5

array([[57216,  3241],
       [ 1188,   145]], dtype=int64)

In [22]:
tab5.diagonal().sum()/tab5.sum()

0.9283217349085613

In [64]:
#over sampling
mod_x=mod.drop(["label"],axis=1)
mod_y=mod.label

In [65]:
from sklearn.model_selection import train_test_split
mod_x_train,mod_x_test,mod_y_train,mod_y_test=train_test_split(mod_x,mod_y,test_size=0.2,random_state=101)

In [66]:
mod_X=pd.concat([mod_x_train,mod_y_train],axis=1)

In [67]:
df_major=mod_X[mod_X.label==0]
df_minor=mod_X[mod_X.label==1]

In [229]:
from sklearn.utils import resample
mod1=resample(df_minor,replace=True,n_samples=600000,random_state=100)

In [230]:
mod_new=pd.concat([df_major,mod1])

In [231]:
mod_new.label.value_counts()

1    600000
0    233965
Name: label, dtype: int64

In [232]:
mod_new_xtrain=mod_new.drop(["label"],axis=1)
mod_new_ytrain=mod_new.label

In [233]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
abc=AdaBoostClassifier(DecisionTreeClassifier(),n_estimators=20)
abc.fit(mod_new_xtrain,mod_new_ytrain)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                          

In [234]:
pred6=abc.predict(mod_x_test)

In [235]:
from sklearn.metrics import confusion_matrix
tab6=confusion_matrix(pred6,mod_y_test)
tab6

array([[38749,  2209],
       [19655,  1177]], dtype=int64)

In [236]:
tab6.diagonal().sum()/tab6.sum()

0.6461563359766953

In [237]:
1177/(1177+2209)

0.3476077968103958

In [238]:
38749/(38749+19655)

0.6634648311759469

In [70]:
mod.label.value_counts()

0    292369
1     16579
Name: label, dtype: int64

In [71]:
16579+5000

21579

In [13]:
#feature selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
test=SelectKBest(score_func=chi2,k='all')
fited=test.fit(mod_x,mod_y)
fited.scores_

array([4.33889538e+02, 1.75326627e+02, 4.25175418e+01, 9.39411316e+02,
       1.70429341e+02, 7.50700965e+01, 7.01368737e+02, 4.04147715e+02,
       7.84064521e+01, 1.41253552e+07, 1.23734625e+03, 1.05445792e+02,
       1.46126623e+02])